name: Deploy DocC

on:
  workflow_dispatch:
 
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target SwiftLI \
            --disable-indexing \
            --transform-for-static-hosting \
            --output-path ./docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: "https://kc-2001ms.github.io/SwiftLI/documentation/swiftli/"

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
