# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    name: Build and Test (macOS)
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: compnerd/gha-setup-swift@main
      with:
        swift-version: "swift-6.1.2-release"
        swift-build: "6.1.2-RELEASE"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
